#!/bin/sh

# To be run inside of docker container, built in CI.  See Dockerfile for
# directory structure

# First argument is address of S3_BUCKET
S3_BUCKET="$1"

cd /app

aws s3 sync ./src s3://$S3_BUCKET --acl public-read --cache-control "max-age=86400"
